Repository alexandruantochi/reddit-up, pull requests merged in 2023-03, with the labels that each got.

#21 feat: correct dupe-checker api and implement it into the frontend
  api/dupe-checker/index.ts
  ui/src/app/components/user-page/user-page.component.ts
  ui/src/app/services/content-retriever.service.ts
Labels: feature

#20 Release next version
  api/dupe-checker/function.json
  api/dupe-checker/index.ts
  api/dupe-checker/sample.dat
  ui/src/app/app.component.css
  ui/src/app/app.component.html
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/components/search-component/search-component.component.css
  ui/src/app/components/search-component/search-component.component.html
  ui/src/app/components/search-component/search-component.component.ts
  ui/src/app/components/user-page/user-page.component.ts
  ui/src/app/constants/types.ts
  ui/src/app/services/content-retriever.service.ts
  ui/src/assets/latest-updates.txt
  ui/src/index.html
  ui/src/styles.css
Labels: release

#28 project can be debugged from root folder; ui, api or ui&api
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  api/.vscode/extensions.json
  api/.vscode/launch.json
  api/.vscode/tasks.json
  ui/.vscode/tasks.json
Labels: operational

#29 Add View History
  ui/src/app/app-routing.module.ts
  ui/src/app/app.component.css
  ui/src/app/app.component.html
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/components/start/start.component.css
  ui/src/app/components/start/start.component.html
  ui/src/app/components/start/start.component.spec.ts
  ui/src/app/components/start/start.component.ts
  ui/src/app/components/user-page/user-page.component.ts
  ui/src/app/services/content-retriever.service.ts
  ui/src/app/services/view-history.service.spec.ts
  ui/src/app/services/view-history.service.ts
  ui/src/assets/Up.png
  ui/src/assets/up.ico
  ui/src/index.html
  ui/src/styles.css
Labels: feature
